#!/usr/bin/env bash
# configuring subdomains and displaying it

_config () {
	s=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
	echo "$2 $s" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  _config "$1" "www"
  _config "$1" "lb-01"
  _config "$1" "web-01"
  _config "$1" "web-02"
elif [ "$#" == 2 ]
then
  _config "$1" "$2"
fi
