#!/usr/bin/env bash
# transfer file from client to server using scp

if [ $# -ne 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1

fi

# assign command-line arguments to variables
PATH_FILE=$1
IP=$2
USERNAME=$3
PATH_SSHKEY=$4

# transfer the file to the user's home directory on server using scp

scp -i "$PATH_SSHKEY" -o StrictHostKeyChecking=no "$PATH_FILE" "$USERNAME@$IP:~/"
