#!/usr/bin/env bash
# Intalls nginx server
sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

reprn="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com permanent;"
sudo sed -i "s/server_name _;/$reprn/" /etc/nginx/sites-enabled/default

sudo service nginx restart
