#!/usr/bin/env bash
# Intalls nginx server
sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

reprn="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com permanent;"
sudo sed -i "s/server_name _;/$reprn/" /etc/nginx/sites-enabled/default

# Script to create error page and redirect for error 404
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
reprn="listen 80 default_server;\n\terrorpage 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$reprn/" /etc/nginx/sites-enabled/default

# restart the server
sudo service nginx restart
