#!/usr/bin/env bash
# bash script to display the content of the file /etc/passwd

while IFS=: read -r username _ uid _ home _; do
	# print required info's
	echo "$username:$uid:$home"
done < /etc/passwd
