#!/usr/bin/env bash
# display "Hi" at the 9th iteration Usage: while and if
i=0
while [ $i -le 9 ]; do
	if [ $i -eq 8 ]; then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	((i++))
done
