#!/usr/bin/env bash
# bash script that loop from 1-10 Usage While, if, else, elif
i=0 # intialize counter
while [ $i -lt 10 ]; do
	if [ $i -eq 3 ]; then
		echo "bad luck"
	elif [ $i -eq 7 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
