#!/usr/bin/env bash
# bash script that gives information about school file.

if [ -e "school" ]; then
	echo "school file exists"

	# check if the file is empty
	if [ -s "school" ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi

	# check if the file is regular file
	if [ -f "school" ]; then
		echo "school is a regular file"
	else
		:
	fi
else
	echo "school file does not exist"
fi
