#!/usr/bin/env bash
# Fix container so that Nginx is running as the nginx user.

# set user in config by replace '#user' and the value
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# replace port 80 with 8080 insites-available/default config
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# give owner permission to read and write to configuration file
chmod 644 /etc/nginx/nginx.conf
# apache may interfere with nginx so kill process if it is running
pkill apache2

# start nginx service with the new nginx user
sudo -u nginx service nginx start
