#!/usr/bin/env bash
# Lets create RSA key pair

KEY_NAME="school"
PASSPHRASE="betty"

# Create the RSA key pair with 4096 bits(max)
ssh-keygen -t rsa -b 4096 -C "$KEY_NAME key" -N "$PASSPHRASE" -f "./$KEY_NAME"
